In [1]:
import pandas as pd

In [3]:
retail = pd.read_csv("../retailFiles/retail_2016_2017.csv", parse_dates=["date"])
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [4]:
retail.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 100.4 MB

In [6]:
retail.assign(
    year= retail["date"].dt.year,
    month= retail["date"].dt.month,
    day_of_week= retail["date"].dt.day_of_week
)

,id,date,store_nbr,family,sales,onpromotion,year,month,day_of_week
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,2016,1,4
1,1945945,2016-01-01,1,BABY CARE,0.000,0,2016,1,4
2,1945946,2016-01-01,1,BEAUTY,0.000,0,2016,1,4
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,2016,1,4
4,1945948,2016-01-01,1,BOOKS,0.000,0,2016,1,4
...,...,...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,2017,8,1
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,2017,8,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,2017,8,1
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,2017,8,1
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,2017,8,1

### Datetime Format Codes

| Category | Directive | Meaning | Example |
|---|---|---|---|
| **Year** | `%Y` | 4-digit year | `2026` |
| | `%y` | 2-digit year (zero-padded) | `26` |
| **Month** | `%m` | Month number (zero-padded) | `09` |
| | `%B` | Full month name | `September` |
| | `%b` | Abbreviated month name | `Sep` |
| **Day** | `%d` | Day of the month (zero-padded) | `23` |
| | `%j` | Day of the year (zero-padded) | `266` |
| **Time** | `%H` | Hour (24-hour clock) | `14` |
| | `%I` | Hour (12-hour clock) | `02` |
| | `%M` | Minute (zero-padded) | `05` |
| | `%S` | Second (zero-padded) | `09` |
| | `%p` | AM or PM | `PM` |
| **Sub-seconds** | `%f` | Microseconds (6 digits) | `123456` |
| | `%N` | Nanoseconds (9 digits, **pandas specific**) | `123456789` |
| **Compound** | `%F` | Shortcut for `%Y-%m-%d` | `2026-09-23` |
| | `%X` | Locale's appropriate time representation | `14:05:09` |
| | `%D` | Shortcut for `%m/%d/%y` | `09/23/26` |